version: '3.7'

services:
  api:
    container_name: api_container
    build: ./api
    ports:
      - 8080:8080
  web:
    container_name: web_container
    build: ./web
    ports:
      - 3000:80
    depends_on:
      - api

